export const GET_DATA_STUDENT = "GET_DATA_STUDENTS";
export const FAILED_GET_DATA_STUDENT = "FAILED_GET_DATA_STUDENTS";
export const REMOVE_GET_DETAIL_STUDENT = "REMOVE_GET_DETAIL_STUDENT";
export const GET_DETAIL_STUDENT = "GET_DETAIL_STUDENT";
export const FAILED_GET_DETAIL_STUDENT = "FAILED_GET_DETAIL_STUDENT";
export const DELETE_DATA_STUDENT = "DELETE_DATA_STUDENT";
export const FAILED_DELETE_DATA_STUDENT = "FAILED_DELETE_DATA_STUDENT";
export const ADD_DATA_STUDENT = "ADD_DATA_STUDENT";
export const FAILED_ADD_DATA_STUDENT_VALIDATION =
  "FAILED_ADD_DATA_STUDENT_VALIDATION";
export const FAILED_ADD_DATA_STUDENT_MESSAGE_ERROR =
  "FAILED_ADD_DATA_STUDENT_MESSAGE_ERROR";
export const FAILED_UPDATE_STUDENT_VALIDATION =
  "FAILED_UPDATE_STUDENT_VALIDATION";
export const FAILED_UPDATE_STUDENT_MESSAGE_ERROR =
  "FAILED_UPDATE_STUDENT_MESSAGE_ERROR";
export const SUCCESS_UPDATE_STUDENT = "SUCCESS_UPDATE_STUDENT";

export const GET_DATA_ACTIVITY = "GET_DATA_ACTIVITY";
export const FAILED_GET_DATA_ACTIVITY = "FAILED_GET_DATA_ACTIVITY";

export const GET_DATA_SCHEDULE = "GET_DATA_SCHEDULE";
export const FAILED_GET_DATA_SCHEDULE = "FAILED_GET_DATA_SCHEDULE";
export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const REMOVE_ADD_SCHEDULE = "REMOVE_ADD_SCHEDULE";
export const FAILED_ADD_SCHEDULE = "FAILED_ADD_SCHEDULE";
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const FAILED_DELETE_SCHEDULE = "FAILED_DELETE_SCHEDULE";
export const REQUEST_DETAIL_SCHEDULE = "REQUEST_DETAIL_SCHEDULE";
export const GET_DETAILS_SCHEDULE = "GET_UPDATE_DETAILS_SCHEDULE";
export const FAILED_UPDATE_DETAILS_SCHEDULE = "FAILED_UPDATE_DETAILS_SCHEDULE";
export const REMOVE_UPDATE_DETAILS_SCHEDULE = "REMOVE_UPDATE_DETAILS_SCHEDULE";

export const GET_DATA_TEACHER = "GET_DATA_TEACHER";
export const FAILED_GET_DATA_TEACHER = "FAILED_GET_DATA_TEACHER";
export const GET_DETAIL_TEACHER = "GET_DETAIL_TEACHER";
export const FAILED_GET_DETAIL_TEACHER = "FAILED_GET_DETAIL_TEACHER";
export const REQUEST_DATA_SINGLE_TEACHER = "REQUEST_DATA_SINGLE_TEACHER";
export const SUCCESS_UPDATE_TEACHER = " SUCCESS_UPDATE_TEACHER ";
export const FAILED_UPDATE_TEACHER_VALIDATION =
  "FAILED_UPDATE_TEACHER_VALIDATION";
export const FAILED_UPDATE_TEACHER_MESSAGE = "FAILED_UPDATE_TEACHER_MESSAGE";
export const REMOVE_GET_DETAIL_TEACHER = "REMOVE_GET_DETAIL_TEACHER";
export const ADD_DATA_TEACHER = "ADD_DATA_TEACHER";
export const FAILED_ADD_DATA_TEACHER_VALIDATION =
  "FAILED_ADD_DATA_TEACHER_VALIDATION";
export const FAILED_ADD_DATA_TEACHER_MESSAGE =
  "FAILED_ADD_DATA_TEACHER_MESSAGE";
export const DELETE_DATA_TEACHER = "DELETE_DATA_TEACHER";
export const FAILED_DELETE_DATA_TEACHER = "FAILED_DELETE_DATA_TEACHER";

export const GET_DATA_CLASSROOM = "GET_DATA_CLASSROOM";
export const FAILED_GET_DATA_CLASSROM = "FAILED_GET_DATA_CLASSROM";
export const ADD_DATA_CLASSROOM = "ADD_DATA_CLASSROOM";
export const REMOVE_ADD_CLASSROOM = "REMOVE_ADD_CLASSROOM";
export const FAILED_ADD_DATA_CLASSROOM = "FAILED_ADD_DATA_CLASSROOM";
export const DELETE_DATA_CLASSROM = "DELETE_DATA_CLASSROM";
export const FAILED_DELETE_DATA_CLASSROM = "FAILED_DELETE_DATA_CLASSROM";
export const REQUEST_DETAIL_CLASSROOM = "REQUEST_DETAIL_CLASSROOM";
export const GET_DETAIL_CLASSROOM = "GET_DETAIL_CLASSROOM";
export const FAILED_GET_DETAIL_CLASSROOM = "FAILED_GET_DETAIL_CLASSROOM";
export const SUCCESS_UPDATE_CLASSROOM = " SUCCESS_UPDATE_CLASSROOM ";
export const FAILED_UPDATE_CLASSROOM = "FAILED_UPDATE_CLASSROOM";
export const REMOVE_DETAIL_CLASSROOM = "REMOVE_DETAIL_CLASSROOM";

export const VERIFY_TEACHER = "VERIFY_TEACHER";
export const FAILED_VERIFY_TEACHER = "FAILED_VERIFY_TEACHER";
export const REQUEST_LOGIN_DATA = "REQUEST_LOGIN_DATA";
export const LOGIN_START = "LOGIN_START";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const VERIFY_TEACHER_NEXT_STEP = "VERIFY_TEACHER_NEXT_STEP";
export const FAILED_VERIFY_TEACHER_NEXT_STEP =
  "FAILED_VERIFY_TEACHER_NEXT_STEP";

export const GET_DATA_ACCOUNT = "GET_DATA_ACCOUNT";
export const FAILED_GET_DATA_ACCOUNT = "FAILED_GET_DATA_ACCOUNT";
export const CONFIRMASTION_ACCOUNT = "CONFIRMASTION_ACCOUNT";
export const FAILED_CONFIRMASTION_ACCOUNT = "FAILED_CONFIRMASTION_ACCOUNT";

export const LOAD_USER_DATA = "LOAD_USER_DATA";
export const FAILED_LOAD_DATA_USER = "FAILED_LOAD_DATA_USER";
export const REMOVE_DATA_USER = "REMOVE_DATA_USER";

export const ADD_DATA_SCORE = "ADD_DATA_SCORE";
export const FAILED_ADD_DATA_SCORE = "FAILED_ADD_DATA_SCORE";
export const REMOVE_ADD_DATA_SCORE = "REMOVE_ADD_DATA_SCORE";

export const GET_INFORMATION_STUDENT = "GET_INFORMATION_STUDENT";
export const FAILED_GET_INFORMATION_STUDENT = "FAILED_GET_INFORMATION_STUDENT";

// registrasi staff
export const START_REGISTRASION_STAFF = "START_REGISTRASION_STAFF";
export const SUCCESS_REGISTRASION_STAFF = "SUCCESS_REGISTRASION_STAFF";
export const FAILED_REGISTRASION_STAFF = "FAILED_REGISTRASION_STAFF";

// teacher state
export const GET_DATA_SCORE = "GET_DATA_SCORE";
export const FAILED_GET_DATA_SCORE = "FAILED_GET_DATA_SCORE";

export const GET_DETAIL_SCORE = "GET_DETAIL_SCORE";
export const FAILED_GET_DETAIL_SCORE = "FAILED_GET_DETAIL_SCORE";
