// class
// get
export const GET_DATA_CLASSROOM = "GET_DATA_CLASSROOM";
export const FAILED_GET_DATA_CLASSROOM = "FAILED_GET_DATA_CLASSROOM";
// add
export const START_ADD_DATA_CLASSROOM = "START_ADD_DATA_CLASSROOM";
export const SUCCESS_ADD_DATA_CLASSROOM = "SUCCESS_ADD_DATA_CLASSROOM";
export const FAILED_ADD_DATA_CLASSROOM = "FAILED_ADD_DATA_CLASSROOM";
export const REMOVE_ADD_CLASSROOM = "REMOVE_ADD_CLASSROOM";
// update
export const START_UPDATE_DATA_CLASSROOM = "START_UPDATE_DATA_CLASSROOM";
export const SUCCESS_UPDATE_DATA_CLASSROOM = "SUCCESS_UPDATE_DATA_CLASSROOM";
export const FAILED_UPDATE_DATA_CLASSROOM = "FAILED_UPADATE_DATA_CLASSROOM";
// detail
export const GET_DETAIL_CLASSROOM = "GET_DETAIL_CLASSROOM";
export const FAILED_GET_DETAIL_CLASSROOM = "FAILED_GET_DETAIL_CLASSROOM";
export const REMOVE_DETAIL_CLASSROOM = "REMOVE_DETAIL_CLASSROOM";
// delete
export const DELETE_DATA_CLASSROM = "DELETE_DATA_CLASSROM";
export const FAILED_DELETE_DATA_CLASSROM = "FAILED_DELETE_DATA_CLASSROM";

// schedule
// add
export const START_ADD_SCHEDULE = "START_ADD_SCHEDULE";
export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const FAILED_ADD_SCHEDULE = "FAILED_ADD_SCHEDULE";
export const REMOVE_ADD_SCHEDULE = "REMOVE_ADD_SCHEDULE";
// get
export const GET_DATA_SCHEDULE = "GET_DATA_SCHEDULE";
export const FAILED_GET_DATA_SCHEDULE = "FAILED_GET_DATA_SCHEDULE";
