export const START_VALIDASI_NO_IDENTITY = "START_VALIDASI_NO_IDENTITY";
export const SUCCESS_VALIDASI_NO_IDENTITY = "SUCCESS_VALIDASI_NO_IDENTITY";
export const FAILED_VALIDASI_NO_IDENTITY = "FAILED_VALIDASI_NO_IDENTITY";

export const START_PASSWORD_VALIDASI = "START_PASSWORD_VALIDASI";
export const SUCCESS_PASSWORD_VALIDASI = "SUCCESS_PASSWORD_VALIDASI";
export const FAILED_PASSWORD_VALIDASI = "FAILED_PASSWORD_VALIDASI";

export const GET_SCORE = "GET_SCORE";
export const FAILED_GET_SCORE = "FAILED_GET_SCORE";
