// class
// get
export const GET_DATA_CLASSROOM = "GET_DATA_CLASSROOM";
export const FAILED_GET_DATA_CLASSROOM = "FAILED_GET_DATA_CLASSROOM";
// add
export const START_ADD_DATA_CLASSROOM = "START_ADD_DATA_CLASSROOM";
export const SUCCESS_ADD_DATA_CLASSROOM = "SUCCESS_ADD_DATA_CLASSROOM";
export const FAILED_ADD_DATA_CLASSROOM = "FAILED_ADD_DATA_CLASSROOM";
export const REMOVE_ADD_CLASSROOM = "REMOVE_ADD_CLASSROOM";
// update
export const START_UPDATE_DATA_CLASSROOM = "START_UPDATE_DATA_CLASSROOM";
export const SUCCESS_UPDATE_DATA_CLASSROOM = "SUCCESS_UPDATE_DATA_CLASSROOM";
export const FAILED_UPDATE_DATA_CLASSROOM = "FAILED_UPADATE_DATA_CLASSROOM";
export const REMOVE_UPDATE_DATA_CLASSROOM = "REMOVE_UPDATE_DATA_CLASSROOM";
// detail
export const GET_DETAIL_CLASSROOM = "GET_DETAIL_CLASSROOM";
export const FAILED_GET_DETAIL_CLASSROOM = "FAILED_GET_DETAIL_CLASSROOM";
export const REMOVE_DETAIL_CLASSROOM = "REMOVE_DETAIL_CLASSROOM";
// delete
export const DELETE_DATA_CLASSROM = "DELETE_DATA_CLASSROM";
export const FAILED_DELETE_DATA_CLASSROM = "FAILED_DELETE_DATA_CLASSROM";

// schedule
// add
export const START_ADD_SCHEDULE = "START_ADD_SCHEDULE";
export const ADD_SCHEDULE = "ADD_SCHEDULE";
export const FAILED_ADD_SCHEDULE = "FAILED_ADD_SCHEDULE";
export const REMOVE_ADD_SCHEDULE = "REMOVE_ADD_SCHEDULE";
// get
export const GET_DATA_SCHEDULE = "GET_DATA_SCHEDULE";
export const FAILED_GET_DATA_SCHEDULE = "FAILED_GET_DATA_SCHEDULE";
// delete
export const DELETE_SCHEDULE = "DELETE_SCHEDULE";
export const FAILED_DELETE_SCHEDULE = "FAILED_DELETE_SCHEDULE";
// detail
export const GET_DETAIL_SCHEDULE = "GET_DETAIL_SCHEDULE";
export const FAILED_GET_DETAIL_SCHEDULE = "FAILED_GET_DETAIL_SCHEDULE";
export const REMOVE_GET_DETAIL_SCHEDULE = "REMOVE_GET_DETAIL_SCHEDULE";
// update
export const START_UPDATE_DATA_SCHEDULE = "START_UPDATE_DATA_SCHEDULE";
export const SUCCESS_UPDATE_DATA_SCHEDULE = "SUCCESS_UPDATE_DATA_SCHEDULE";
export const FAILED_UPDATE_DATA_SCHEDULE = "FAILED_UPADATE_DATA_SCHEDULE";
export const REMOVE_UPDATE_DATA_SCHEDULE = "REMOVE_UPADATE_DATA_SCHEDULE";

// student
// get
export const GET_DATA_STUDENT = "GET_DATA_STUDENT";
export const FAILED_GET_DATA_STUDENT = "FAILED_GET_DATA_STUDENT";
// add
export const START_ADD_STUDENT = "START_ADD_STUDENT";
export const ADD_STUDENT = "ADD_STUDENT";
export const FAILED_ADD_STUDENT = "FAILED_ADD_STUDENT";
export const REMOVE_ADD_STUDENT = "REMOVE_ADD_STUDENT";
// detail
export const GET_DETAIL_STUDENT = "GET_DETAIL_STUDENT";
export const FAILED_GET_DETAIL_STUDENT = "FAILED_GET_DETAIL_STUDENT";
export const REMOVE_GET_DETAIL_STUDENT = "REMOVE_GET_DETAIL_STUDENT";
// update
export const START_UPDATE_DATA_STUDENT = "START_UPDATE_DATA_STUDENT";
export const SUCCESS_UPDATE_DATA_STUDENT = "SUCCESS_UPDATE_DATA_STUDENT";
export const FAILED_UPDATE_DATA_STUDENT = "FAILED_UPADATE_DATA_STUDENT";
export const REMOVE_UPDATE_DATA_STUDENT = "REMOVE_UPADATE_DATA_SCHEDULE";
// delete
export const DELETE_DATA_STUDENT = "DELETE_DATA_STUDENT";
export const FAILED_DELETE_DATA_STUDENT = "FAILED_DELETE_DATA_STUDENT";

// account
export const GET_DETAIL_ACCOUNT = "GET_DETAIL_ACCOUNT";
export const FAILED_DETAIL_ACCOUNT = "FAILED_DETAIL_ACCOUNT";

export const START_UPDATE_PASSWORD = "START_UPDATE_PASSWORD";
export const SUCCESS_UPDATE_PASSWORD = "SUCCESS_UPDATE_PASSWORD";
export const FAILED_UPDATE_PASSWORD = "FAILED_UPDATE_PASSWORD";

export const SUCCESS_DELETE_ACCOUNT = "SUCCESS_DELETE_ACCOUT";
export const FAILED_DELETE_ACCOUNT = "FAILED_DELETE_ACCOUT";
