// register
export const START_VERIFY_TEACHER = "START_VERIFY_TEACHER";
export const SUCCESS_VERIFY_TEACHER = "SUCCESS_VERIFY_TEACHER";
export const FAILED_VERIFY_TEACHER = "FAILED_VERIFY_TEACHER";
export const RESET_VERIFY_TEACHER = "RESET_VERIFY_TEACHER";

export const START_INPUT_PASSWORD = "START_INPUT_PASSWORD";
export const SUCCESS_INPUT_PASSWORD = "SUCCESS_INPUT_PASSWORD";
export const FAILED_INPUT_PASSWORD = "FAILED_INPUT_PASSWORD";
