// register
export const START_VERIFY_TEACHER = "START_VERIFY_TEACHER";
export const SUCCESS_VERIFY_TEACHER = "SUCCESS_VERIFY_TEACHER";
export const FAILED_VERIFY_TEACHER = "FAILED_VERIFY_TEACHER";
export const RESET_VERIFY_TEACHER = "RESET_VERIFY_TEACHER";
